# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [37]:
import numpy as np

a = np.arange(15).reshape(3, 5)

print('list(a): ', list(a))  
print('tolist(): ', a.tolist())
#list(a) 只會把第一層的元素轉換為 List; tolist() 則可以將多層的 array 都轉換為 List


list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [23]:
# 記得先 Import 正確的套件

'''
Your Code
'''

'\nYour Code\n'

In [28]:

a = np.random.randint(10, size=6) 
print(a) #列印陣列
print(a.ndim) #陣列有多少維度：1
print(a.shape) #每個維度的大小：6
print(a.size) #陣列當中有幾個元素：6
print(a.dtype) #陣列中的資料型態：int32
print(a.itemsize) # 陣列中每個元素佔用的空間：4
print(len(a)) #陣列中數值長度：6
print(type(a)) #陣列類型：numpy.ndarray


[9 5 4 2 2 4]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [29]:
b = np.random.randint(10, size=(3,4)) 

print(b) #列印陣列
print(b.ndim) #陣列有多少維度
print(b.shape) #每個維度的大小
print(b.size) #陣列當中有幾個元素
print(b.dtype) #陣列中的資料型態
print(b.itemsize) # 陣列中每個元素佔用的空間
print(len(b)) #陣列中數值長度
print(type(b)) #陣列類型

[[6 9 6 8]
 [7 1 7 4]
 [4 8 9 3]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [30]:
c = np.random.randint(10, size=(2,3,2)) 

print(c) #列印陣列
print(c.ndim) #陣列有多少維度
print(c.shape) #每個維度的大小
print(c.size) #陣列當中有幾個元素
print(c.dtype) #陣列中的資料型態
print(c.itemsize) # 陣列中每個元素佔用的空間
print(len(c)) #陣列中數值長度
print(type(c)) #陣列類型

[[[8 2]
  [2 0]
  [1 2]]

 [[1 2]
  [3 6]
  [6 1]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [51]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[2, 6, 2, 4, 5, 4]
[2, 6, 2, 4, 5, 4]


In [52]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[1, 9, 6, 8], [7, 7, 3, 0], [6, 0, 4, 7]]
[array([1, 9, 6, 8]), array([7, 7, 3, 0]), array([6, 0, 4, 7])]


In [53]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[5, 2], [7, 4], [0, 8]], [[8, 8], [7, 8], [5, 9]]]
[array([[5, 2],
       [7, 4],
       [0, 8]]), array([[8, 8],
       [7, 8],
       [5, 9]])]


In [54]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[2, 6, 2, 4, 5, 4]
[[1, 9, 6, 8], [7, 7, 3, 0], [6, 0, 4, 7]]
[[[5, 2], [7, 4], [0, 8]], [[8, 8], [7, 8], [5, 9]]]
