# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [6]:
import numpy as np

print(np.zeros((2, 3)))
print(np.empty((2, 3)))
# np.empty不需要給定起始值，可以建立給定形狀的陣列，元素值則會隨機給定。
# 因此相較於 np.zeros， np.empty 給出的數值並非真的 0，而是接近 0 的數值

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [92]:
a = np.random.rand(2, 3)
a = a * 100
np.round(a)


array([[88., 42., 35.],
       [19.,  3., 57.]])

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [128]:
#方法一
a = np.random.rand(2, 3)
m = 20
n = 40
a = 20 + a * 20
np.round(a)

array([[38., 24., 31.],
       [26., 24., 27.]])

In [129]:
#方法二

from numpy.random import default_rng
rng = default_rng()

m = 20
n = 40
a = rng.integers(m, n, size=(2, 3))
a

array([[33, 34, 23],
       [23, 28, 34]], dtype=int64)