# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [56]:
#作法一

import numpy as np

a = np.arange( 1,12 )
b = []
for i in a:
   if i <= 2:
    i= i * 1
    b.append(i)

for i in a:
   if i >= 3 and i <= 6:
    i= i * -1
    b.append(i)
    
for i in a:
   if i > 6:
    i= i * 1
    b.append(i)
    
print(b)



[1, 2, -3, -4, -5, -6, 7, 8, 9, 10, 11]


In [58]:
#作法二

a = np.arange( 1,12 )
a [2:6]= -a[2:6]
print(a)

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [60]:
A = np.random.rand(3, 6)
print(A)
print(A[A>0.5].size)


[[0.15288361 0.28897842 0.7672302  0.3794068  0.28459118 0.14612286]
 [0.26381301 0.42636046 0.68005597 0.56693619 0.45582371 0.08507984]
 [0.35717855 0.3059625  0.37500659 0.50569177 0.34695322 0.15506848]]
4
