# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
import numpy as np 

a = np.arange(6)
print(a.sum()) 
print(np.sum(a))
print(sum(a))

15
15
15


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [4]:
A = np.random.rand(5, 5)
A = (A - A.min())/(A.max() - A.min())
print(A)


[[0.34603133 0.62157786 0.06430413 0.02166502 0.6071619 ]
 [0.24495886 1.         0.85760154 0.685047   0.09134991]
 [0.97887749 0.47129402 0.42438085 0.33166948 0.3297289 ]
 [0.94430264 0.93143308 0.41065383 0.18109518 0.71519176]
 [0.91420949 0.         0.30491491 0.67957367 0.42696461]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [55]:
a = np.random.randint(1,100,10)

a[np.argmax(a)] = -1
print(a)


[70 18 78 64 64 31 65 72 -1  5]
